# Generated by Django 5.0.4 on 2024-05-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doktorlar',
            fields=[
                ('doktorID', models.IntegerField(primary_key=True, serialize=False)),
                ('doktor_ad', models.CharField(max_length=50)),
                ('doktor_soyad', models.CharField(max_length=50)),
                ('doktor_uzmanlikAlani', models.CharField(max_length=50)),
                ('doktor_calistigiHastane', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hastalar',
            fields=[
                ('hastaID', models.IntegerField(primary_key=True, serialize=False)),
                ('hasta_ad', models.CharField(max_length=50)),
                ('hasta_soyad', models.CharField(max_length=50)),
                ('hasta_dogumTarihi', models.DateTimeField()),
                ('hasta_cinsiyet', models.CharField(max_length=6)),
                ('hasta_telefonNo', models.CharField(max_length=14)),
                ('hasta_adres', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sifreler',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Yonetici',
            fields=[
                ('YoneticiID', models.IntegerField(primary_key=True, serialize=False)),
                ('yonetici_password', models.CharField(max_length=10)),
            ],
        ),
    ]
