# Generated by Django 5.0.4 on 2024-05-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yonetici',
            old_name='yonetici_password',
            new_name='yonetici_sifre',
        ),
    ]
