# Generated by Django 5.0.4 on 2024-05-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_yonetici_password_yonetici_yonetici_sifre'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainAppDoktorlar',
            fields=[
                ('doktorid', models.IntegerField(db_column='doktorID', primary_key=True, serialize=False)),
                ('doktor_ad', models.CharField(max_length=50)),
                ('doktor_soyad', models.CharField(max_length=50)),
                ('doktor_uzmanlikalani', models.CharField(db_column='doktor_uzmanlikAlani', max_length=50)),
                ('doktor_calistigihastane', models.CharField(db_column='doktor_calistigiHastane', max_length=50)),
            ],
            options={
                'db_table': 'main_app_doktorlar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainAppHastalar',
            fields=[
                ('hastaid', models.IntegerField(db_column='hastaID', primary_key=True, serialize=False)),
                ('hasta_ad', models.CharField(max_length=50)),
                ('hasta_soyad', models.CharField(max_length=50)),
                ('hasta_dogumtarihi', models.DateTimeField(db_column='hasta_dogumTarihi')),
                ('hasta_cinsiyet', models.CharField(max_length=6)),
                ('hasta_telefonno', models.CharField(db_column='hasta_telefonNo', max_length=14)),
                ('hasta_adres', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'main_app_hastalar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainAppSifreler',
            fields=[
                ('userid', models.IntegerField(db_column='userID', primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'main_app_sifreler',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainAppYonetici',
            fields=[
                ('yoneticiid', models.IntegerField(db_column='YoneticiID', primary_key=True, serialize=False)),
                ('yonetici_sifre', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'main_app_yonetici',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Randevular',
            fields=[
                ('randevuid', models.AutoField(db_column='RandevuID', primary_key=True, serialize=False)),
                ('tarih', models.DateField(blank=True, db_column='Tarih', null=True)),
                ('saat', models.TimeField(blank=True, db_column='Saat', null=True)),
            ],
            options={
                'db_table': 'randevular',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tibbiraporlar',
            fields=[
                ('raporid', models.AutoField(db_column='RaporID', primary_key=True, serialize=False)),
                ('raportarihi', models.DateField(blank=True, db_column='RaporTarihi', null=True)),
                ('raporicerigi', models.TextField(blank=True, db_column='RaporIcerigi', null=True)),
            ],
            options={
                'db_table': 'tibbiraporlar',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='doktorlar',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='hastalar',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sifreler',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='yonetici',
            options={'managed': False},
        ),
    ]
